feat: add `@deno/shim-deno` package (#68)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,7 +19,7 @@ jobs:
     - uses: actions/checkout@v2
       with:
         submodules: true
-    - run: (cd packages/deno.ns/third_party/deno; git submodule update --init --depth=1 test_util/std)
+    - run: (cd packages/shim-deno/third_party/deno; git submodule update --init --depth=1 test_util/std)
       shell: bash
     - uses: actions/setup-node@v2
       with:
@@ -35,12 +35,12 @@ jobs:
     - run: npm ci  --ignore-scripts
     - run: npm run --silent test --workspaces
     - run: npm run --silent prepare --workspaces
-    - run: cd packages/deno.ns && tools/missing.ts || echo "Some items are missing"
+    - run: cd packages/shim-deno && tools/missing.ts || echo "Some items are missing"
       if: matrix.os == 'ubuntu-latest'
-    - run: cd packages/deno.ns && tools/untested.sh
+    - run: cd packages/shim-deno && tools/untested.sh
       if: matrix.os == 'ubuntu-latest'
     - name: npm publish
-      if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/') && github.repository == 'denoland/deno.ns'
+      if: matrix.os == 'ubuntu-latest' && startsWith(github.ref, 'refs/tags/') && github.repository == 'denoland/node-shims'
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-      run: cd packages/deno.ns && npm publish
+      run: cd packages/shim-deno && npm publish
